name: Deploy

on:
  push:
    branches:
      - dev-front

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Nginx to serve angular to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "69a2cd61-e881-4f88-a812-de98c849c5a5"
          heroku_app_name: "back-dev-lonic-27"
          heroku_email: "jl.lopez77@uniandes.edu.co"
          usedocker: true
          appdir: flaskr

  front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Nginx to serve angular to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "69a2cd61-e881-4f88-a812-de98c849c5a5"
          heroku_app_name: "test-front-lonic-27"
          heroku_email: "jl.lopez77@uniandes.edu.co"
          usedocker: true
          appdir: front-end/tutorial-canciones
          docker_build_args: |
            ENV_TYPE
        env:
          ENV_TYPE: pruebas
