name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push Lonic-xx branch
  push:
    branches:
    - 'feature/**'
    - 'development'
  pull_request:
    branches: development
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  backend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install python3, pip and backend
        run: |
          cd flaskr
          sudo pip install -r requirements.txt
      - name: Test with unittest
        run: |
            sudo apt install python-pytest
            python -m unittest
      - name: Execution app
        run: flask run &
          
  frontend:
    needs: backend
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Install frontend angular
        run: |
          cd front-end/tutorial-canciones
          sudo apt install -y nodejs
          sudo npm install npm@latest -g
          sudo npm install -g @angular/cli
      # - name: Test with unittest
      #  run: |
      #   cd front-end/tutorial-canciones 
      #   ng test --browsers MyHeadLessBrowser
      - name: Run App
        run: |
          cd front-end/tutorial-canciones
          ng serve
