name: Release version
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  page_build:
  release:
    types: created
    uses: "marvinpinto/action-automatic-releases@latest"
    with:
      repo_token: "${{ secrets.GITHUB_TOKEN }}"
      prerelease: false
